name: Publish
run-name: Publish ${{github.event.inputs.package}} from ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Target
        required: true
        options:
          - common
          - telemetry
          - chains-list

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
          cache: 'yarn'

      - name: Get deployment information
        run: |
          echo "Branch: ${BRANCH_NAME}"
          echo "Package: ${{github.event.inputs.package}}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish
        working-directory: ./packages/${{ github.event.inputs.package }}/
        run: |
          npm config set access public -ws=false -iwr 
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPMJS_TOKEN }} -ws=false -iwr 
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm run build:turbo
          npm publish
