name: Publish

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Target
        required: true
        options:
          - ankr-global-menu
          - ankr-infra
          - provider
          - staking-sdk

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.PUSH_TO_PROTECTED_BRANCH_GITHUB_CREDENTIALS}}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          cache: 'yarn'

      - name: Get deployment information
        run: |
          echo "Branch: ${BRANCH_NAME}"
          echo "Package: ${{github.event.inputs.package}}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish
        working-directory: ./packages/${{ github.event.inputs.package }}/
        run: |
          npm config set access public
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm run build
          npm publish
